all:
  hosts:
    node1:
      ansible_host: 10.0.2.15
      ip: 10.0.2.15
      access_ip: 10.0.2.15
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
